import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'

import type { Metadata } from 'next'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

import { auth } from '@/auth'
import { Toaster } from '@/components/ui/sonner'

export const metadata: Metadata = {
	title: 'image viewer',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const session = await auth()
	return (
		<SessionProvider session={session}>
			<html lang="en" className="h-full">
				<body className={`${inter.className} h-full`}>
					<Toaster />
					{children}
				</body>
			</html>
		</SessionProvider>
	)
}
